import Footer from "@/components/Footer";
import IntroScreen from "@/components/IntroScreen";
import Navbar from "@/components/Navbar";
import Side from "@/components/Side";
import "@/styles/globals.css";
import { Montserrat } from "next/font/google";
import Head from "next/head";

const montserrat = Montserrat({ subsets: ["latin"], variable: "--font-mont" });

export default function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Kamil Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        className={`${montserrat.variable} font-mont bg-light w-full min-h-screen`}
      >
        
        <Navbar />
        <Side/>
        <Component {...pageProps} />
      
      </main>
    </>
  );
}
